name: Blazor WebAssembly

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.x.x
    - name: Restore dependencies and build
      run: |
        cd Imc
        dotnet restore
        dotnet build --no-restore
    - name: Test
      run: |
        dotnet test --no-build --verbosity normal
    - name: Publish Blazor WebAssembly app
      run: |
        dotnet publish -c Release -o dist
    - name: Deploy to GitHub Pages
      run: |
        git subtree push --prefix dist origin gh-pages
