name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build and Deploy
      run: |
        cd Imc/dist/wwwroot
        git init
        git checkout gh-pages || git checkout --orphan gh-pages
        git rm -rf .
        cp -r . ../../  # Mova os arquivos de volta para o diretório raiz do branch gh-pages
        git add .
        git commit -m "Deploy to GitHub Pages"
        git push --force origin gh-pages

