name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"

    - name: Build and Deploy
      run: |
        cd Imc/dist/wwwroot
    
        # Inicializa o repositório Git no diretório se não existir
        if [ ! -d ".git" ]; then
          git init
          git checkout -b gh-pages
        else
          # Se o repositório já existir, continua no branch gh-pages
          git checkout gh-pages
        fi
    
        # Adiciona e faz o commit dos arquivos
        git add .
        git commit -m "Deploy to GitHub Pages"
    
        # Configura as credenciais para o push usando o token de acesso embutido
        git remote add origin-with-token "https://${{ github.token }}@github.com/${{ github.repository }}.git"
        git push --force origin-with-token gh-pages
